Feature/enemy
lucasvdiepen/ProefExamen pull request #7
Opened 2024-03-06 08:26 UTC by JoepEilander

first two enemy spritesheets and flat sprites

2024-03-07 09:23 UTC, PiterGroot requested changes

2024-03-07 09:23 UTC, PiterGroot commented on Assets/Scripts/Framework/Gameplay/LaneSystem/DeadNote.cs
> +                _spriteRenderer = gameObject.GetComponent<SpriteRenderer>();
GetComponent in `Awake`

2024-03-07 09:23 UTC, PiterGroot commented on Assets/Scripts/Framework/Gameplay/LaneSystem/DeadNote.cs
> +    public class DeadNote : MonoBehaviour
Missing summery also needs [RequireComponent(typeof(SpriteRenderer))]

2024-03-07 09:23 UTC, PiterGroot commented on Assets/Scripts/Framework/Gameplay/LaneSystem/DeadNote.cs
> +        public void SetDeadNoteValues(Sprite sprite, Transform newTransform)
Missing summery

2024-03-07 09:23 UTC, PiterGroot commented on Assets/Scripts/Framework/Gameplay/LaneSystem/DeadNote.cs
> +using ProefExamen.Framework.Gameplay.Values;
ProefExamen namespaces need to be under every other namspace

2024-03-07 09:23 UTC, PiterGroot commented on Assets/Scripts/Framework/Gameplay/LaneSystem/Lane.cs
> +        private GameObject notePrefab;
```suggestion
        private GameObject _notePrefab;
```

2024-03-07 09:23 UTC, PiterGroot commented on Assets/Scripts/Framework/Gameplay/LaneSystem/Note.cs
> +                _animator = gameObject.GetComponent<Animator>();
```cs
           if(_animator == null)
                _animator = gameObject.GetComponent<Animator>();

            if (_spriteRenderer == null)
                _spriteRenderer = gameObject.GetComponent<SpriteRenderer>();
```

GetComponent in `Awake`

2024-03-07 09:23 UTC, PiterGroot commented on Assets/Scripts/Framework/Gameplay/LaneSystem/Note.cs
> +        public void HitNote()
Missing summery

2024-03-08 08:42 UTC, lucasvdiepen requested changes
Looks good! Could you please remove all the underscores in the file names except for the prefixes and suffixes. Also remove the 512x512 in file names.

2024-03-08 08:42 UTC, lucasvdiepen commented on Assets/Art/2D/Sprites/Enemies/Spritesheets/AC_Enemy_Blue_512x512_0.controller
Remove 512x512 and underscores in file name

2024-03-08 08:42 UTC, lucasvdiepen commented on Assets/Art/2D/Sprites/Enemies/Spritesheets/AC_Enemy_Green_512x512_0.controller
Remove 512x512 and underscores in file name

2024-03-08 08:42 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/LaneSystem/Note.cs
> +                _animator.speed = _animationSpeed / SessionValues.Instance.travelTime;
Remove unnecessary else statement
```suggestion

            _animator.speed = _animationSpeed / SessionValues.Instance.travelTime;
```

2024-03-08 09:11 UTC, lucasvdiepen approved these changes

2024-03-08 09:11 UTC, merged